defmodule BotArmyYoutubeManager.Learning.ParaWriter do
  @moduledoc """
  Generates and writes analytics summaries to PARA filesystem.

  Creates markdown summaries with video metrics, anomalies, and learning insights.
  Structures output as /YouTube/Analytics/YYYY-MM/weekly-WEEK.md
  """

  require Logger
  import Ecto.Query

  alias BotArmyYoutubeManager.{
    Repo,
    Schemas.VideoMetric,
    Schemas.LearningOutcome,
    Schemas.LearningOptimizationProposal
  }

  def write_to_para(path, markdown) do
    Logger.info("Writing PARA summary", path: path)

    content_b64 = Base.encode64(markdown)

    payload =
      Jason.encode!(%{
        "schema_version" => "1.0",
        "relative_path" => path,
        "content_base64" => content_b64,
        "mode" => "write"
      })

    with {:ok, conn} <-
           GenServer.call(BotArmyRuntime.NATS.Connection, :get_connection, 5_000),
         {:ok, raw} <- Gnat.request(conn, "para.fs.write", payload, receive_timeout: 15_000),
         {:ok, resp} <- Jason.decode(raw.body) do
      if resp["ok"] do
        Logger.info("PARA write successful", path: path)
        {:ok, path}
      else
        {:error, resp["error"]}
      end
    end
  end

  def generate_para_summary(start_date, end_date) do
    Logger.info("Generating PARA summary for #{start_date} to #{end_date}")

    # Gracefully handle test mode where Repo is not started
    metrics = fetch_metrics(start_date, end_date)
    anomalies = fetch_anomalies(start_date, end_date)
    proposals = fetch_pending_proposals()

    markdown = build_summary_markdown(metrics, anomalies, proposals, start_date, end_date)
    path = build_para_path(start_date)

    {:ok, %{path: path, markdown: markdown}}
  rescue
    e in DBConnection.ConnectionError ->
      Logger.warning("Repo not available in test mode: #{inspect(e)}")
      # Fallback markdown in test mode
      markdown = build_summary_markdown([], [], [], start_date, end_date)
      path = build_para_path(start_date)
      {:ok, %{path: path, markdown: markdown}}
  end

  defp fetch_metrics(start_date, end_date) do
    from(vm in VideoMetric,
      where: vm.date >= ^start_date and vm.date <= ^end_date,
      order_by: [desc: vm.views]
    )
    |> Repo.all()
  end

  defp fetch_anomalies(start_date, end_date) do
    from(lo in LearningOutcome,
      where: lo.recorded_at >= ^DateTime.new!(start_date, ~T[00:00:00]),
      where: lo.recorded_at <= ^DateTime.new!(end_date, ~T[23:59:59]),
      order_by: [desc: lo.recorded_at]
    )
    |> Repo.all()
  end

  defp fetch_pending_proposals do
    from(lop in LearningOptimizationProposal,
      where: lop.status == "pending",
      order_by: [desc: lop.proposed_at]
    )
    |> Repo.all()
    |> Enum.take(5)
  end

  defp build_summary_markdown(metrics, anomalies, proposals, start_date, end_date) do
    """
    # YouTube Analytics Summary
    **Period:** #{start_date} to #{end_date}

    ## Overview

    - **Videos Tracked:** #{length(metrics)}
    - **Anomalies Detected:** #{length(anomalies)}
    - **Optimization Proposals:** #{length(proposals)}

    ## Top Performing Videos

    #{top_videos_section(metrics)}

    ## Anomalies Detected

    #{anomalies_section(anomalies)}

    ## Learning Insights

    #{learning_insights_section(proposals)}

    ## Metrics Summary

    #{metrics_summary_section(metrics)}

    ---
    *Generated by YouTube Manager Bot v#{bot_version()} at #{DateTime.utc_now()}*
    """
  end

  defp top_videos_section(metrics) do
    if Enum.empty?(metrics) do
      "No video data available for this period."
    else
      metrics
      |> Enum.take(5)
      |> Enum.with_index(1)
      |> Enum.map(fn {metric, idx} ->
        engagement =
          Map.get(metric.engagement, "likes", 0) + Map.get(metric.engagement, "comments", 0)

        "#{idx}. **#{metric.video_id}** — #{metric.views} views, #{engagement} engagement, #{metric.watch_time_minutes}m watched"
      end)
      |> Enum.join("\n")
    end
  end

  defp anomalies_section(anomalies) do
    if Enum.empty?(anomalies) do
      "No anomalies detected."
    else
      anomalies
      |> Enum.take(10)
      |> Enum.map(fn outcome ->
        status = if outcome.was_correct, do: "✓ Validated", else: "✗ Incorrect"
        "- **#{outcome.category}/#{outcome.decision}** (#{outcome.item_id}) — #{status}"
      end)
      |> Enum.join("\n")
    end
  end

  defp learning_insights_section(proposals) do
    if Enum.empty?(proposals) do
      "Learning system is optimizing. Check back for insights."
    else
      proposals
      |> Enum.map(fn proposal ->
        "- **#{proposal.category}** (#{proposal.type}) — #{proposal.reason}"
      end)
      |> Enum.join("\n")
    end
  end

  defp metrics_summary_section(metrics) do
    if Enum.empty?(metrics) do
      "No metrics available."
    else
      total_views = Enum.reduce(metrics, 0, fn m, acc -> acc + m.views end)
      total_watch_time = Enum.reduce(metrics, 0.0, fn m, acc -> acc + m.watch_time_minutes end)

      avg_ctr =
        Enum.reduce(metrics, 0.0, fn m, acc -> acc + m.click_through_rate end) / length(metrics)

      """
      | Metric | Value |
      |--------|-------|
      | Total Views | #{total_views} |
      | Total Watch Time | #{total_watch_time |> Float.round(1)}m |
      | Avg CTR | #{avg_ctr |> Float.round(2)}% |
      | Videos Tracked | #{length(metrics)} |
      """
    end
  end

  defp build_para_path(start_date) do
    year = start_date.year
    month = start_date.month |> Integer.to_string() |> String.pad_leading(2, "0")
    week = Calendar.ISO.week_of_year(start_date) |> elem(0)

    "projects/YouTube/Analytics/#{year}-#{month}/weekly-#{week}.md"
  end

  defp bot_version do
    case Application.fetch_env(:bot_army_youtube_manager, :version) do
      {:ok, version} -> version
      :error -> "unknown"
    end
  end
end
