{application,octo_fetch,
             [{config_mtime,1779229162},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,inets,public_key,
                             castore,ssl_verify_fun]},
              {description,"Download, verify, and extract GitHub release artifacts effortlessly right from Elixir"},
              {modules,['Elixir.OctoFetch','Elixir.OctoFetch.Downloader',
                        'Elixir.OctoFetch.Test']},
              {registered,[]},
              {vsn,"0.5.0"}]}.
